[build]
  base = "Front/schedulerpdv-front"
  command = "npm run build && node ./scripts/write-config.js"
  publish = "dist/schedulerpdv-front"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
